# ワークフロー名
name: ビルド確認

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  # Androidビルド確認
  build-android:
    name: Androidビルド
    runs-on: ubuntu-latest
    steps:
      - name: コードのチェックアウト
        uses: actions/checkout@v4

      - name: JDKのセットアップ
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Gradleのセットアップ
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: false

      - name: Androidビルド実行
        run: ./gradlew :composeApp:assembleDebug --no-daemon

      - name: APKのアップロード
        uses: actions/upload-artifact@v4
        with:
          name: reminderparrot-android-debug
          path: composeApp/build/outputs/apk/debug/*.apk
          retention-days: 7

  # iOSビルド確認
  build-ios:
    name: iOSビルド
    runs-on: macos-latest
    steps:
      - name: コードのチェックアウト
        uses: actions/checkout@v4

      - name: JDKのセットアップ
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Gradleのセットアップ
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: false

      - name: Kotlin Nativeのキャッシュ
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-konan-

      - name: iOSフレームワークのビルド
        run: ./gradlew :composeApp:compileKotlinIosX64 --no-daemon

      - name: iOSアプリのビルド
        run: |
          cd iosApp
          xcodebuild -project iosApp.xcodeproj -scheme iosApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' -configuration Debug -derivedDataPath build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - name: iOSアプリのアーカイブ作成
        run: |
          cd iosApp/build/Build/Products/Debug-iphonesimulator
          mkdir -p Payload
          cp -r iosApp.app Payload/
          zip -r reminderparrot-ios-simulator.zip Payload

      - name: iOSアプリのアップロード
        uses: actions/upload-artifact@v4
        with:
          name: reminderparrot-ios-simulator
          path: iosApp/build/Build/Products/Debug-iphonesimulator/reminderparrot-ios-simulator.zip
          retention-days: 7